<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('materiales')->insert([
            [
                'nombre' => 'Resina compuesta A2',
                'descripcion' => 'Resina fotocurada color A2 para restauraciones',
                'unidad_medida' => 'jeringa',
                'stock_actual' => 15.00,
                'stock_minimo' => 5.00,
                'precio_unitario' => 85.00,
                'proveedor' => 'Dental Supply Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Anestesia lidocaína 2%',
                'descripcion' => 'Cartucho de anestesia local 1.8ml con epinefrina',
                'unidad_medida' => 'cartucho',
                'stock_actual' => 50.00,
                'stock_minimo' => 20.00,
                'precio_unitario' => 8.00,
                'proveedor' => 'Pharma Dental La Paz',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Guantes de látex talla M',
                'descripcion' => 'Caja con 100 guantes estériles',
                'unidad_medida' => 'caja',
                'stock_actual' => 8.00,
                'stock_minimo' => 3.00,
                'precio_unitario' => 45.00,
                'proveedor' => 'MediPro Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Guantes de nitrilo talla M',
                'descripcion' => 'Caja con 100 guantes sin látex',
                'unidad_medida' => 'caja',
                'stock_actual' => 5.00,
                'stock_minimo' => 2.00,
                'precio_unitario' => 65.00,
                'proveedor' => 'MediPro Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Gasas estériles 5x5cm',
                'descripcion' => 'Paquete de 100 unidades',
                'unidad_medida' => 'paquete',
                'stock_actual' => 12.00,
                'stock_minimo' => 5.00,
                'precio_unitario' => 25.00,
                'proveedor' => 'MediPro Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cemento dental temporal',
                'descripcion' => 'Cemento provisional para restauraciones temporales',
                'unidad_medida' => 'frasco',
                'stock_actual' => 6.00,
                'stock_minimo' => 2.00,
                'precio_unitario' => 120.00,
                'proveedor' => 'Dental Supply Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Agujas dentales 27G',
                'descripcion' => 'Caja con 100 agujas desechables',
                'unidad_medida' => 'caja',
                'stock_actual' => 4.00,
                'stock_minimo' => 2.00,
                'precio_unitario' => 95.00,
                'proveedor' => 'Pharma Dental La Paz',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Alginato dental rosado',
                'descripcion' => 'Bolsa de 450g para impresiones',
                'unidad_medida' => 'bolsa',
                'stock_actual' => 10.00,
                'stock_minimo' => 3.00,
                'precio_unitario' => 75.00,
                'proveedor' => 'Dental Supply Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Fresas diamantadas surtidas',
                'descripcion' => 'Set de 10 fresas para alta velocidad',
                'unidad_medida' => 'set',
                'stock_actual' => 8.00,
                'stock_minimo' => 3.00,
                'precio_unitario' => 180.00,
                'proveedor' => 'Instrumental Dental SRL',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eyectores de saliva',
                'descripcion' => 'Bolsa con 100 unidades desechables',
                'unidad_medida' => 'bolsa',
                'stock_actual' => 7.00,
                'stock_minimo' => 3.00,
                'precio_unitario' => 35.00,
                'proveedor' => 'MediPro Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Rollos de algodón',
                'descripcion' => 'Bolsa con 500 rollos',
                'unidad_medida' => 'bolsa',
                'stock_actual' => 6.00,
                'stock_minimo' => 2.00,
                'precio_unitario' => 40.00,
                'proveedor' => 'MediPro Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Desinfectante para superficies',
                'descripcion' => 'Frasco spray 500ml',
                'unidad_medida' => 'frasco',
                'stock_actual' => 10.00,
                'stock_minimo' => 4.00,
                'precio_unitario' => 30.00,
                'proveedor' => 'Productos de Limpieza SRL',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Brackets metálicos',
                'descripcion' => 'Set completo para una arcada (10 piezas)',
                'unidad_medida' => 'set',
                'stock_actual' => 20.00,
                'stock_minimo' => 8.00,
                'precio_unitario' => 250.00,
                'proveedor' => 'Ortho Dental Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Arcos de ortodoncia NiTi',
                'descripcion' => 'Arco de níquel-titanio .016',
                'unidad_medida' => 'unidad_medida',
                'stock_actual' => 15.00,
                'stock_minimo' => 6.00,
                'precio_unitario' => 45.00,
                'proveedor' => 'Ortho Dental Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbijos quirúrgicos tricapa',
                'descripcion' => 'Caja con 50 unidades desechables',
                'unidad_medida' => 'caja',
                'stock_actual' => 12.00,
                'stock_minimo' => 5.00,
                'precio_unitario' => 40.00,
                'proveedor' => 'MediPro Bolivia',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
