<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PacientesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pacientes')->insert([
            [
                'nombre_completo' => 'Juan Carlos Pérez Mamani',
                'fecha_nacimiento' => '1985-03-15',
                'genero' => 'masculino',
                'telefono' => '71234567',
                'email' => 'juan.perez@email.com',
                'direccion' => 'Av. 6 de Agosto #2345, Zona Sopocachi',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'María Pérez - 72345678',
                'tipo_sangre' => 'O+',
                'alergias' => 'Penicilina',
                'condiciones_medicas' => 'Hipertensión arterial controlada',
                'observaciones' => 'Paciente regular desde 2020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Ana María Quispe Rodríguez',
                'fecha_nacimiento' => '1992-07-22',
                'genero' => 'femenino',
                'telefono' => '73456789',
                'email' => 'ana.quispe@email.com',
                'direccion' => 'Calle Potosí #567, Zona Miraflores',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Pedro Quispe - 74567890',
                'tipo_sangre' => 'A+',
                'alergias' => 'Ninguna conocida',
                'condiciones_medicas' => null,
                'observaciones' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Roberto Carlos Mendoza Silva',
                'fecha_nacimiento' => '1978-11-30',
                'genero' => 'masculino',
                'telefono' => '75678901',
                'email' => 'roberto.mendoza@email.com',
                'direccion' => 'Av. Arce #3456, Zona San Jorge',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Laura Mendoza - 76789012',
                'tipo_sangre' => 'B+',
                'alergias' => 'Anestesia local (lidocaína)',
                'condiciones_medicas' => 'Diabetes tipo 2',
                'observaciones' => 'Requiere cuidado especial en procedimientos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Patricia Eugenia Rojas Condori',
                'fecha_nacimiento' => '2000-05-18',
                'genero' => 'femenino',
                'telefono' => '77890123',
                'email' => 'patricia.rojas@email.com',
                'direccion' => 'Calle Murillo #789, Zona Central',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Carmen Condori - 78901234',
                'tipo_sangre' => 'O-',
                'alergias' => null,
                'condiciones_medicas' => null,
                'observaciones' => 'Primera visita en octubre 2024',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Luis Fernando Gutiérrez Choque',
                'fecha_nacimiento' => '1995-12-08',
                'genero' => 'masculino',
                'telefono' => '79012345',
                'email' => 'luis.gutierrez@email.com',
                'direccion' => 'Av. Ballivián #1234, Zona Calacoto',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Rosa Choque - 70123456',
                'tipo_sangre' => 'AB+',
                'alergias' => null,
                'condiciones_medicas' => null,
                'observaciones' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Carmen Rosa Mamani Apaza',
                'fecha_nacimiento' => '1988-09-25',
                'genero' => 'femenino',
                'telefono' => '71345678',
                'email' => 'carmen.mamani@email.com',
                'direccion' => 'Calle Sucre #456, Zona San Pedro',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'José Apaza - 72456789',
                'tipo_sangre' => 'A-',
                'alergias' => 'Ibuprofeno',
                'condiciones_medicas' => 'Embarazo (segundo trimestre)',
                'observaciones' => 'Solo tratamientos seguros para embarazo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Miguel Ángel Flores Ticona',
                'fecha_nacimiento' => '2010-02-14',
                'genero' => 'masculino',
                'telefono' => '73567890',
                'email' => null,
                'direccion' => 'Av. Buenos Aires #678, Zona Villa Fátima',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'María Ticona (madre) - 74678901',
                'tipo_sangre' => 'O+',
                'alergias' => null,
                'condiciones_medicas' => null,
                'observaciones' => 'Paciente pediátrico - requiere acompañamiento',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Sofía Isabel Vargas López',
                'fecha_nacimiento' => '1990-06-30',
                'genero' => 'femenino',
                'telefono' => '75789012',
                'email' => 'sofia.vargas@email.com',
                'direccion' => 'Calle 21 de Calacoto #234, Zona Calacoto',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Ricardo Vargas - 76890123',
                'tipo_sangre' => 'B-',
                'alergias' => null,
                'condiciones_medicas' => null,
                'observaciones' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Jorge Eduardo Sánchez Morales',
                'fecha_nacimiento' => '1982-04-12',
                'genero' => 'masculino',
                'telefono' => '77901234',
                'email' => 'jorge.sanchez@email.com',
                'direccion' => 'Av. Costanera #890, Zona Cota Cota',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Elena Morales - 78012345',
                'tipo_sangre' => 'A+',
                'alergias' => 'Látex',
                'condiciones_medicas' => 'Asma bronquial',
                'observaciones' => 'Usar guantes sin látex',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_completo' => 'Daniela Paola Cruz Mamani',
                'fecha_nacimiento' => '1998-08-20',
                'genero' => 'femenino',
                'telefono' => '79123456',
                'email' => 'daniela.cruz@email.com',
                'direccion' => 'Calle México #345, Zona Sopocachi',
                'ciudad' => 'La Paz',
                'contacto_emergencia' => 'Pablo Cruz - 70234567',
                'tipo_sangre' => 'O+',
                'alergias' => null,
                'condiciones_medicas' => null,
                'observaciones' => 'Estudiante universitaria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
